/**
 * Seed script: inserts 20 realistic dummy products into MongoDB.
 * Run via:  npm run seed
 */

const mongoose = require("mongoose");
require("dotenv").config();

// ─── Inline minimal schema (avoids import-path issues) ─────────────────────
const ProductSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    title: { type: String, required: true },
    price: { type: Number, required: true },
    discountPrice: { type: Number, default: 0 },
    description: String,
    shortDescription: String,
    image: { type: String, required: true },
    gallery: [String],
    category: { type: String, required: true },
    subCategory: String,
    brand: { type: String, required: true },
    stock: { type: Number, required: true },
    sku: { type: String, unique: true, sparse: true },
    lowStockThreshold: { type: Number, default: 5 },
    trackQuantity: { type: Boolean, default: true },
    weight: Number,
    dimensions: { length: Number, width: Number, height: Number },
    requiresShipping: { type: Boolean, default: true },
    seoTitle: String,
    seoDescription: String,
    slug: { type: String, unique: true, sparse: true },
    youtubeLink: String,
    status: {
      type: String,
      enum: ["Draft", "Active", "Archived"],
      default: "Draft",
    },
    visibility: {
      type: String,
      enum: ["Public", "Private", "Password Protected"],
      default: "Public",
    },
    attributes: {
      size: { type: Boolean, default: false },
      color: { type: Boolean, default: false },
      material: { type: Boolean, default: false },
    },
    variations: [
      {
        size: String,
        color: String,
        material: String,
        price: Number,
        stock: Number,
        sku: String,
      },
    ],
    specs: [{ key: String, value: String }],
    tags: [String],
    rating: { type: Number, default: 0 },
    numReviews: { type: Number, default: 0 },
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
  },
  { timestamps: true }
);

// ─── Helpers ────────────────────────────────────────────────────────────────
function img(query) {
  const encoded = encodeURIComponent(query);
  return `https://source.unsplash.com/400x400/?${encoded}`;
}

function slug(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
}

// ─── Main ───────────────────────────────────────────────────────────────────
async function main() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("✅  Connected to MongoDB");

  // Find any existing user to assign as owner
  const UserSchema = new mongoose.Schema({ _id: mongoose.Schema.Types.ObjectId, role: String }, { strict: false });
  let User;
  try { User = mongoose.model("User"); } catch { User = mongoose.model("User", UserSchema); }

  const vendor = await User.findOne({ role: "Vendor" }).lean() || await User.findOne().lean();
  if (!vendor) {
    console.error("❌  No user found in database. Please create a vendor account first.");
    process.exit(1);
  }
  const userId = vendor._id;
  console.log(`👤  Using user: ${vendor._id} (${vendor.name || vendor.email || "unknown"})`);

  let Product;
  try { Product = mongoose.model("Product"); } catch { Product = mongoose.model("Product", ProductSchema); }

  const products = [
    {
      name: "Men's Classic Oxford Shirt",
      title: "Premium Cotton Oxford Shirt for Men",
      price: 1299,
      discountPrice: 999,
      description: "A timeless Oxford shirt crafted from 100% premium cotton. Perfect for both casual and semi-formal occasions.",
      shortDescription: "Classic Oxford shirt in premium cotton.",
      image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&q=80",
      gallery: [
        "https://images.unsplash.com/photo-1604644401890-0bd678c83788?w=400&q=80",
        "https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?w=400&q=80",
      ],
      category: "Clothing",
      subCategory: "Men",
      brand: "Fabindia",
      stock: 85,
      sku: "MEN-OXSHIRT-001",
      lowStockThreshold: 10,
      weight: 0.3,
      dimensions: { length: 30, width: 25, height: 3 },
      seoTitle: "Men's Classic Oxford Shirt | Fabindia",
      seoDescription: "Buy premium Oxford shirts for men at best prices.",
      slug: "mens-classic-oxford-shirt",
      status: "Active",
      visibility: "Public",
      attributes: { size: true, color: true, material: false },
      variations: [
        { size: "S", color: "White", price: 999, stock: 20 },
        { size: "M", color: "White", price: 999, stock: 30 },
        { size: "L", color: "Blue", price: 999, stock: 25 },
        { size: "XL", color: "Blue", price: 1099, stock: 10 },
      ],
      specs: [
        { key: "Fabric", value: "100% Cotton" },
        { key: "Fit", value: "Regular Fit" },
        { key: "Collar", value: "Oxford Button-Down" },
      ],
      tags: ["shirt", "men", "cotton", "oxford", "formal"],
      rating: 4.5,
      numReviews: 42,
    },
    {
      name: "Women's Floral Kurta",
      title: "Ethnic Floral Print Kurta for Women",
      price: 899,
      discountPrice: 699,
      description: "Beautiful floral print kurta made from breathable cotton. Perfect for everyday wear and festive occasions.",
      shortDescription: "Ethnic floral kurta in breathable cotton.",
      image: "https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400&q=80",
      gallery: [
        "https://images.unsplash.com/photo-1677187869754-89e2ca90bedc?w=400&q=80",
      ],
      category: "Clothing",
      subCategory: "Women",
      brand: "Biba",
      stock: 120,
      sku: "WOM-KURTA-002",
      lowStockThreshold: 15,
      weight: 0.25,
      dimensions: { length: 32, width: 24, height: 2 },
      seoTitle: "Women's Floral Kurta | Biba",
      seoDescription: "Shop ethnic floral kurtas for women online.",
      slug: "womens-floral-kurta",
      status: "Active",
      visibility: "Public",
      attributes: { size: true, color: true, material: false },
      variations: [
        { size: "S", color: "Pink", price: 699, stock: 30 },
        { size: "M", color: "Pink", price: 699, stock: 40 },
        { size: "L", color: "Yellow", price: 699, stock: 30 },
        { size: "XL", color: "Yellow", price: 749, stock: 20 },
      ],
      specs: [
        { key: "Fabric", value: "Cotton" },
        { key: "Occasion", value: "Casual / Festive" },
      ],
      tags: ["kurta", "women", "ethnic", "floral", "cotton"],
      rating: 4.3,
      numReviews: 58,
    },
    {
      name: "4K Smart LED TV 55\"",
      title: "55 Inch 4K Ultra HD Smart LED TV",
      price: 42999,
      discountPrice: 36999,
      description: "Experience cinema-quality visuals at home with this 55-inch 4K UHD Smart TV featuring Dolby Vision and built-in Android.",
      shortDescription: "55\" 4K Smart TV with Dolby Vision and Android OS.",
      image: "https://images.unsplash.com/photo-1593784991095-a205069470b6?w=400&q=80",
      gallery: [
        "https://images.unsplash.com/photo-1461151304267-38231e7e1f7b?w=400&q=80",
      ],
      category: "Electronics",
      subCategory: "Televisions",
      brand: "Sony",
      stock: 25,
      sku: "ELEC-TV4K-003",
      lowStockThreshold: 5,
      weight: 18.5,
      dimensions: { length: 124, width: 73, height: 9 },
      seoTitle: "55\" 4K Smart LED TV | Sony",
      seoDescription: "Buy Sony 55 inch 4K Smart LED TV at the best price.",
      slug: "4k-smart-led-tv-55",
      status: "Active",
      visibility: "Public",
      attributes: { size: false, color: false, material: false },
      specs: [
        { key: "Resolution", value: "3840 x 2160 (4K UHD)" },
        { key: "OS", value: "Android 11" },
        { key: "HDR", value: "Dolby Vision, HDR10" },
        { key: "Connectivity", value: "WiFi, Bluetooth, HDMI x3, USB x2" },
      ],
      tags: ["tv", "4k", "smart", "sony", "electronics"],
      rating: 4.7,
      numReviews: 134,
    },
    {
      name: "Wireless Noise-Cancelling Headphones",
      title: "Over-Ear Wireless Headphones with Active Noise Cancellation",
      price: 7999,
      discountPrice: 5999,
      description: "Immerse yourself in music with 40-hour battery life, premium ANC, and studio-quality sound in an ultra-comfortable design.",
      shortDescription: "40-hour ANC wireless headphones.",
      image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80",
      gallery: [
        "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400&q=80",
      ],
      category: "Electronics",
      subCategory: "Audio",
      brand: "Boat",
      stock: 60,
      sku: "ELEC-HDPH-004",
      lowStockThreshold: 8,
      weight: 0.28,
      dimensions: { length: 20, width: 18, height: 8 },
      seoTitle: "Wireless ANC Headphones | Boat",
      seoDescription: "Shop noise-cancelling wireless headphones online.",
      slug: "wireless-anc-headphones",
      status: "Active",
      visibility: "Public",
      attributes: { size: false, color: true, material: false },
      variations: [
        { color: "Black", price: 5999, stock: 30 },
        { color: "Midnight Blue", price: 5999, stock: 20 },
        { color: "Sand Beige", price: 6499, stock: 10 },
      ],
      specs: [
        { key: "Battery Life", value: "40 Hours" },
        { key: "Driver Size", value: "40mm" },
        { key: "Connectivity", value: "Bluetooth 5.2" },
        { key: "ANC", value: "Active Noise Cancellation" },
      ],
      tags: ["headphones", "wireless", "anc", "audio", "bluetooth"],
      rating: 4.4,
      numReviews: 211,
    },
    {
      name: "Stainless Steel Water Bottle",
      title: "Insulated Stainless Steel Water Bottle 1L",
      price: 799,
      discountPrice: 599,
      description: "Double-wall vacuum insulation keeps drinks cold for 24 hours and hot for 12 hours. BPA-free and leak-proof.",
      shortDescription: "1L insulated stainless steel bottle, 24h cold.",
      image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&q=80",
      gallery: [],
      category: "Kitchen & Dining",
      subCategory: "Drinkware",
      brand: "Milton",
      stock: 200,
      sku: "KITCH-BTTLE-005",
      lowStockThreshold: 20,
      weight: 0.35,
      dimensions: { length: 8, width: 8, height: 28 },
      seoTitle: "Insulated Steel Water Bottle | Milton",
      seoDescription: "Buy 1L insulated water bottle online at best price.",
      slug: "stainless-steel-water-bottle-1l",
      status: "Active",
      visibility: "Public",
      attributes: { size: false, color: true, material: false },
      variations: [
        { color: "Black", price: 599, stock: 80 },
        { color: "Silver", price: 599, stock: 70 },
        { color: "Red", price: 649, stock: 50 },
      ],
      specs: [
        { key: "Capacity", value: "1 Litre" },
        { key: "Material", value: "18/8 Stainless Steel" },
        { key: "Cold Retention", value: "24 Hours" },
        { key: "Hot Retention", value: "12 Hours" },
      ],
      tags: ["bottle", "water", "insulated", "steel", "bpa-free"],
      rating: 4.6,
      numReviews: 320,
    },
    {
      name: "Running Sports Shoes",
      title: "Lightweight Mesh Running Sports Shoes for Men",
      price: 2499,
      discountPrice: 1799,
      description: "Ultra-lightweight running shoes with adaptive mesh upper, cushioned midsole, and anti-slip rubber outsole for all terrains.",
      shortDescription: "Lightweight mesh running shoes with cushioned sole.",
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80",
      gallery: [
        "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?w=400&q=80",
      ],
      category: "Footwear",
      subCategory: "Sports",
      brand: "Nike",
      stock: 75,
      sku: "FOOT-RUNSH-006",
      lowStockThreshold: 10,
      weight: 0.45,
      dimensions: { length: 32, width: 12, height: 10 },
      seoTitle: "Men's Running Sports Shoes | Nike",
      seoDescription: "Buy Nike running shoes for men at the best price.",
      slug: "mens-running-sports-shoes",
      status: "Active",
      visibility: "Public",
      attributes: { size: true, color: true, material: false },
      variations: [
        { size: "7", color: "Black/White", price: 1799, stock: 10 },
        { size: "8", color: "Black/White", price: 1799, stock: 20 },
        { size: "9", color: "Blue/Grey", price: 1799, stock: 25 },
        { size: "10", color: "Blue/Grey", price: 1799, stock: 15 },
        { size: "11", color: "Red/Black", price: 1899, stock: 5 },
      ],
      specs: [
        { key: "Upper", value: "Breathable Mesh" },
        { key: "Sole", value: "Rubber Anti-slip" },
        { key: "Closure", value: "Lace-up" },
        { key: "Weight", value: "240g per shoe" },
      ],
      tags: ["shoes", "running", "sports", "nike", "men"],
      rating: 4.5,
      numReviews: 182,
    },
    {
      name: "Wooden Bookshelf 5-Tier",
      title: "5-Tier Engineered Wood Bookshelf with Metal Frame",
      price: 5999,
      discountPrice: 4499,
      description: "Elegant 5-tier bookshelf combining sturdy metal frame with natural wood-finish boards. Easy assembly, perfect for home or office.",
      shortDescription: "Modern 5-tier bookshelf with metal frame.",
      image: "https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400&q=80",
      gallery: [],
      category: "Furniture",
      subCategory: "Storage",
      brand: "Godrej Interio",
      stock: 18,
      sku: "FURN-BKSHF-007",
      lowStockThreshold: 3,
      weight: 14.0,
      dimensions: { length: 80, width: 30, height: 175 },
      seoTitle: "5-Tier Bookshelf | Godrej Interio",
      seoDescription: "Buy 5-tier wooden bookshelf online at best price.",
      slug: "wooden-bookshelf-5-tier",
      status: "Active",
      visibility: "Public",
      attributes: { size: false, color: true, material: false },
      variations: [
        { color: "Walnut Brown", price: 4499, stock: 10 },
        { color: "White", price: 4699, stock: 8 },
      ],
      specs: [
        { key: "Material", value: "Engineered Wood + Metal" },
        { key: "Tiers", value: "5" },
        { key: "Max Load", value: "15 kg per shelf" },
        { key: "Assembly", value: "Required (tools included)" },
      ],
      tags: ["bookshelf", "furniture", "storage", "wood", "home"],
      rating: 4.2,
      numReviews: 67,
    },
    {
      name: "Organic Green Tea",
      title: "Premium Darjeeling Organic Green Tea – 100g",
      price: 499,
      discountPrice: 399,
      description: "Hand-picked from the foothills of Darjeeling, this organic green tea is rich in antioxidants and has a delicate floral aroma.",
      shortDescription: "100g premium Darjeeling organic green tea.",
      image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",
      gallery: [],
      category: "Food & Beverages",
      subCategory: "Tea & Coffee",
      brand: "Twinings",
      stock: 300,
      sku: "FOOD-GRTEA-008",
      lowStockThreshold: 30,
      weight: 0.12,
      dimensions: { length: 10, width: 6, height: 12 },
      seoTitle: "Organic Green Tea Darjeeling | Twinings",
      seoDescription: "Buy premium Darjeeling organic green tea online.",
      slug: "organic-darjeeling-green-tea-100g",
      status: "Active",
      visibility: "Public",
      attributes: { size: false, color: false, material: false },
      specs: [
        { key: "Weight", value: "100g" },
        { key: "Origin", value: "Darjeeling, India" },
        { key: "Certification", value: "USDA Organic" },
        { key: "Brew Temperature", value: "80°C" },
      ],
      tags: ["green-tea", "organic", "darjeeling", "health", "beverage"],
      rating: 4.8,
      numReviews: 450,
    },
    {
      name: "Non-Stick Cookware Set",
      title: "5-Piece Premium Non-Stick Cookware Set with Glass Lids",
      price: 3499,
      discountPrice: 2699,
      description: "Includes kadhai, saucepan, fry pan, and 2 lids. PFOA-free non-stick coating, induction compatible, oven-safe up to 180°C.",
      shortDescription: "5-piece PFOA-free non-stick induction cookware.",
      image: "https://images.unsplash.com/photo-1585837575652-267c041d77d4?w=400&q=80",
      gallery: [],
      category: "Kitchen & Dining",
      subCategory: "Cookware",
      brand: "Prestige",
      stock: 45,
      sku: "KITCH-CWSET-009",
      lowStockThreshold: 5,
      weight: 3.8,
      dimensions: { length: 50, width: 40, height: 30 },
      seoTitle: "Non-Stick Cookware Set 5-Piece | Prestige",
      seoDescription: "Buy 5-piece non-stick cookware set online at best price.",
      slug: "non-stick-cookware-set-5-piece",
      status: "Active",
      visibility: "Public",
      attributes: { size: false, color: false, material: false },
      specs: [
        { key: "Pieces", value: "5 (Kadhai, Saucepan, Fry Pan, 2 Lids)" },
        { key: "Coating", value: "PFOA-Free Non-Stick" },
        { key: "Induction", value: "Compatible" },
        { key: "Oven Safe", value: "Up to 180°C" },
      ],
      tags: ["cookware", "non-stick", "kitchen", "prestige", "induction"],
      rating: 4.4,
      numReviews: 98,
    },
    {
      name: "Yoga Mat with Carry Strap",
      title: "6mm Anti-Slip TPE Yoga Mat with Carrying Strap",
      price: 1299,
      discountPrice: 899,
      description: "Eco-friendly TPE yoga mat with double-sided anti-slip surface, alignment lines, and a free carry strap. 183cm × 61cm.",
      shortDescription: "6mm eco-friendly TPE yoga mat, 183×61cm.",
      image: "https://images.unsplash.com/photo-1593811167562-9cef47bfc4a7?w=400&q=80",
      gallery: [],
      category: "Sports & Fitness",
      subCategory: "Yoga",
      brand: "Boldfit",
      stock: 90,
      sku: "SPORT-YOGA-010",
      lowStockThreshold: 10,
      weight: 0.9,
      dimensions: { length: 183, width: 61, height: 0.6 },
      seoTitle: "Anti-Slip TPE Yoga Mat | Boldfit",
      seoDescription: "Buy 6mm anti-slip yoga mat online at best price.",
      slug: "yoga-mat-tpe-6mm",
      status: "Active",
      visibility: "Public",
      attributes: { size: false, color: true, material: false },
      variations: [
        { color: "Purple", price: 899, stock: 30 },
        { color: "Blue", price: 899, stock: 30 },
        { color: "Black", price: 899, stock: 30 },
      ],
      specs: [
        { key: "Thickness", value: "6mm" },
        { key: "Material", value: "TPE (Eco-friendly)" },
        { key: "Dimensions", value: "183cm × 61cm" },
        { key: "Includes", value: "Free carry strap" },
      ],
      tags: ["yoga", "mat", "fitness", "tpe", "exercise"],
      rating: 4.5,
      numReviews: 176,
    },
    {
      name: "Leather Wallet – RFID Blocking",
      title: "Men's Genuine Leather Slim Wallet with RFID Blocking",
      price: 999,
      discountPrice: 749,
      description: "Slim bifold wallet crafted from genuine full-grain leather. Features 6 card slots, 2 bill compartments, and RFID blocking technology.",
      shortDescription: "Slim genuine leather wallet with RFID protection.",
      image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400&q=80",
      gallery: [],
      category: "Accessories",
      subCategory: "Bags & Wallets",
      brand: "Woodland",
      stock: 150,
      sku: "ACC-WALET-011",
      lowStockThreshold: 15,
      weight: 0.07,
      dimensions: { length: 11, width: 9, height: 1 },
      seoTitle: "RFID Leather Slim Wallet | Woodland",
      seoDescription: "Buy men's RFID blocking genuine leather wallet online.",
      slug: "mens-rfid-leather-wallet",
      status: "Active",
      visibility: "Public",
      attributes: { size: false, color: true, material: true },
      variations: [
        { color: "Dark Brown", material: "Full-Grain Leather", price: 749, stock: 60 },
        { color: "Black", material: "Full-Grain Leather", price: 749, stock: 60 },
        { color: "Tan", material: "Full-Grain Leather", price: 799, stock: 30 },
      ],
      specs: [
        { key: "Material", value: "Full-Grain Leather" },
        { key: "Card Slots", value: "6" },
        { key: "RFID", value: "Blocking Technology" },
        { key: "Style", value: "Slim Bifold" },
      ],
      tags: ["wallet", "leather", "rfid", "men", "accessories"],
      rating: 4.6,
      numReviews: 230,
    },
    {
      name: "Smartphone Stand Wireless Charger",
      title: "15W Fast Wireless Charging Stand for Smartphones",
      price: 1499,
      discountPrice: 1099,
      description: "Universal Qi wireless charger compatible with iPhone and Android. Adjustable angle stand, LED indicator, 15W fast charge.",
      shortDescription: "15W Qi wireless charger stand for all smartphones.",
      image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&q=80",
      gallery: [],
      category: "Electronics",
      subCategory: "Accessories",
      brand: "Anker",
      stock: 110,
      sku: "ELEC-WCHGR-012",
      lowStockThreshold: 10,
      weight: 0.18,
      dimensions: { length: 10, width: 9, height: 12 },
      seoTitle: "15W Wireless Charger Stand | Anker",
      seoDescription: "Buy 15W fast wireless charger for smartphones online.",
      slug: "wireless-charger-stand-15w",
      status: "Active",
      visibility: "Public",
      attributes: { size: false, color: true, material: false },
      variations: [
        { color: "Black", price: 1099, stock: 60 },
        { color: "White", price: 1099, stock: 50 },
      ],
      specs: [
        { key: "Power Output", value: "15W" },
        { key: "Input", value: "USB-C" },
        { key: "Compatibility", value: "Qi-enabled devices" },
        { key: "Features", value: "Adjustable angle, LED indicator" },
      ],
      tags: ["charger", "wireless", "15w", "qi", "smartphone"],
      rating: 4.3,
      numReviews: 145,
    },
    {
      name: "Face Moisturizer SPF 50",
      title: "Daily Hydrating Face Moisturizer with SPF 50 – 50ml",
      price: 649,
      discountPrice: 499,
      description: "Lightweight oil-free moisturizer with broad-spectrum SPF 50 protection. Suitable for all skin types. Dermatologically tested.",
      shortDescription: "Lightweight oil-free moisturizer with SPF 50.",
      image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&q=80",
      gallery: [],
      category: "Beauty & Personal Care",
      subCategory: "Skincare",
      brand: "Neutrogena",
      stock: 250,
      sku: "BEAU-MOIST-013",
      lowStockThreshold: 20,
      weight: 0.1,
      dimensions: { length: 5, width: 5, height: 8 },
      seoTitle: "SPF 50 Face Moisturizer | Neutrogena",
      seoDescription: "Buy daily hydrating face moisturizer with SPF 50 online.",
      slug: "face-moisturizer-spf50",
      status: "Active",
      visibility: "Public",
      attributes: { size: false, color: false, material: false },
      specs: [
        { key: "Volume", value: "50ml" },
        { key: "SPF", value: "50 (Broad Spectrum)" },
        { key: "Skin Type", value: "All skin types" },
        { key: "Tested", value: "Dermatologically tested" },
      ],
      tags: ["moisturizer", "spf50", "skincare", "sunscreen", "face"],
      rating: 4.6,
      numReviews: 310,
    },
    {
      name: "Mechanical Gaming Keyboard",
      title: "TKL Mechanical Gaming Keyboard with RGB Backlight",
      price: 3999,
      discountPrice: 2899,
      description: "Tenkeyless mechanical keyboard with Cherry MX Red switches, per-key RGB lighting, N-key rollover, and a detachable USB-C cable.",
      shortDescription: "TKL RGB mechanical keyboard, Cherry MX Red switches.",
      image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&q=80",
      gallery: [],
      category: "Electronics",
      subCategory: "Computer Peripherals",
      brand: "Keychron",
      stock: 40,
      sku: "ELEC-MKBD-014",
      lowStockThreshold: 5,
      weight: 0.85,
      dimensions: { length: 36, width: 13, height: 4 },
      seoTitle: "TKL Mechanical Gaming Keyboard RGB | Keychron",
      seoDescription: "Buy Keychron TKL mechanical keyboard with RGB online.",
      slug: "tkl-mechanical-gaming-keyboard-rgb",
      status: "Active",
      visibility: "Public",
      attributes: { size: false, color: true, material: false },
      variations: [
        { color: "Space Grey", price: 2899, stock: 20 },
        { color: "Black", price: 2899, stock: 20 },
      ],
      specs: [
        { key: "Layout", value: "Tenkeyless (TKL)" },
        { key: "Switch", value: "Cherry MX Red" },
        { key: "Backlight", value: "Per-key RGB" },
        { key: "Connection", value: "USB-C Wired" },
        { key: "Rollover", value: "N-Key Rollover" },
      ],
      tags: ["keyboard", "mechanical", "gaming", "rgb", "tkl"],
      rating: 4.7,
      numReviews: 88,
    },
    {
      name: "Adjustable Dumbbell Set 2kg-10kg",
      title: "Adjustable Rubber Dumbbell Set for Home Gym (2–10 kg)",
      price: 4499,
      discountPrice: 3399,
      description: "Hex rubber dumbbells with chrome handles. Includes 2kg, 4kg, 6kg, 8kg, and 10kg pairs with a sturdy A-frame rack.",
      shortDescription: "5-pair rubber dumbbell set with A-frame rack.",
      image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80",
      gallery: [],
      category: "Sports & Fitness",
      subCategory: "Gym Equipment",
      brand: "Kore",
      stock: 22,
      sku: "SPORT-DBSET-015",
      lowStockThreshold: 3,
      weight: 60,
      dimensions: { length: 70, width: 30, height: 50 },
      seoTitle: "Adjustable Dumbbell Set 2-10kg | Kore",
      seoDescription: "Buy rubber dumbbell set for home gym at best price.",
      slug: "adjustable-dumbbell-set-2-10kg",
      status: "Active",
      visibility: "Public",
      attributes: { size: false, color: false, material: false },
      specs: [
        { key: "Set Includes", value: "5 pairs (2/4/6/8/10 kg) + rack" },
        { key: "Material", value: "Rubber coated hex" },
        { key: "Handle", value: "Chrome-plated, knurled" },
      ],
      tags: ["dumbbell", "gym", "fitness", "home-gym", "weights"],
      rating: 4.5,
      numReviews: 61,
    },
    {
      name: "Kids' Backpack – School Bag",
      title: "Waterproof Kids' Backpack 18L for School – Dinosaur Print",
      price: 799,
      discountPrice: 599,
      description: "Adorable 18L dinosaur-print school backpack with ergonomic shoulder straps, multiple compartments, and waterproof fabric.",
      shortDescription: "18L waterproof kids' school backpack with fun print.",
      image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80",
      gallery: [],
      category: "Kids",
      subCategory: "School Supplies",
      brand: "Skybags",
      stock: 180,
      sku: "KIDS-BKPCK-016",
      lowStockThreshold: 20,
      weight: 0.5,
      dimensions: { length: 30, width: 15, height: 40 },
      seoTitle: "Kids Waterproof School Backpack | Skybags",
      seoDescription: "Buy cute waterproof school backpack for kids online.",
      slug: "kids-school-backpack-18l-dinosaur",
      status: "Active",
      visibility: "Public",
      attributes: { size: false, color: true, material: false },
      variations: [
        { color: "Green Dinosaur", price: 599, stock: 80 },
        { color: "Blue Dinosaur", price: 599, stock: 60 },
        { color: "Pink Unicorn", price: 599, stock: 40 },
      ],
      specs: [
        { key: "Capacity", value: "18 Litres" },
        { key: "Material", value: "Waterproof Polyester" },
        { key: "Compartments", value: "Main + front pocket + side pockets" },
        { key: "Age", value: "3–10 years" },
      ],
      tags: ["backpack", "kids", "school", "waterproof", "bag"],
      rating: 4.4,
      numReviews: 292,
    },
    {
      name: "Vitamin C Serum",
      title: "20% Vitamin C Brightening Face Serum – 30ml",
      price: 899,
      discountPrice: 699,
      description: "High-potency 20% Vitamin C serum with hyaluronic acid and niacinamide. Brightens skin, reduces dark spots, and boosts collagen.",
      shortDescription: "20% Vitamin C serum for bright, even-toned skin.",
      image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&q=80",
      gallery: [],
      category: "Beauty & Personal Care",
      subCategory: "Skincare",
      brand: "The Ordinary",
      stock: 195,
      sku: "BEAU-VITC-017",
      lowStockThreshold: 20,
      weight: 0.08,
      dimensions: { length: 3, width: 3, height: 10 },
      seoTitle: "20% Vitamin C Face Serum | The Ordinary",
      seoDescription: "Buy a high potency Vitamin C brightening face serum.",
      slug: "vitamin-c-serum-20-percent",
      status: "Active",
      visibility: "Public",
      attributes: { size: false, color: false, material: false },
      specs: [
        { key: "Volume", value: "30ml" },
        { key: "Concentration", value: "20% Vitamin C" },
        { key: "Key Ingredients", value: "Vitamin C, Hyaluronic Acid, Niacinamide" },
        { key: "Skin Type", value: "All Skin Types" },
      ],
      tags: ["serum", "vitamin-c", "brightening", "skincare", "face"],
      rating: 4.7,
      numReviews: 415,
    },
    {
      name: "Scented Soy Candle Set",
      title: "Luxury Hand-Poured Soy Wax Scented Candle Gift Set (Set of 3)",
      price: 1199,
      discountPrice: 899,
      description: "Set of 3 hand-poured soy wax candles in glass jars. Fragrances: Vanilla & Sandalwood, Rose & Patchouli, Ocean Breeze. Burns for 40 hours each.",
      shortDescription: "Set of 3 luxury soy wax candles, 40h burn time.",
      image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400&q=80",
      gallery: [],
      category: "Home Decor",
      subCategory: "Candles & Diffusers",
      brand: "The Fragrance People",
      stock: 85,
      sku: "DECO-CNDLE-018",
      lowStockThreshold: 10,
      weight: 0.75,
      dimensions: { length: 25, width: 10, height: 10 },
      seoTitle: "Luxury Soy Candle Gift Set | The Fragrance People",
      seoDescription: "Buy a set of 3 luxury soy wax scented candles online.",
      slug: "scented-soy-candle-set-3",
      status: "Active",
      visibility: "Public",
      attributes: { size: false, color: false, material: false },
      specs: [
        { key: "Wax", value: "100% Natural Soy Wax" },
        { key: "Burn Time", value: "~40 hours each" },
        { key: "Fragrances", value: "Vanilla & Sandalwood, Rose & Patchouli, Ocean Breeze" },
        { key: "Container", value: "Clear Glass Jar" },
      ],
      tags: ["candle", "soy", "gift", "home-decor", "aroma"],
      rating: 4.8,
      numReviews: 173,
    },
    {
      name: "Bluetooth Portable Speaker",
      title: "360° Waterproof Portable Bluetooth Speaker with 12h Battery",
      price: 2799,
      discountPrice: 1999,
      description: "IPX7 waterproof portable speaker with 360° surround sound, 12-hour playtime, and a built-in power bank to charge your devices.",
      shortDescription: "IPX7 waterproof speaker, 360° sound, 12h battery.",
      image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&q=80",
      gallery: [],
      category: "Electronics",
      subCategory: "Audio",
      brand: "JBL",
      stock: 55,
      sku: "ELEC-BTSPK-019",
      lowStockThreshold: 8,
      weight: 0.54,
      dimensions: { length: 9, width: 9, height: 18 },
      seoTitle: "Portable Bluetooth Speaker IPX7 | JBL",
      seoDescription: "Buy JBL waterproof portable Bluetooth speaker online.",
      slug: "bluetooth-portable-speaker-360",
      status: "Active",
      visibility: "Public",
      attributes: { size: false, color: true, material: false },
      variations: [
        { color: "Black", price: 1999, stock: 20 },
        { color: "Teal", price: 1999, stock: 20 },
        { color: "Red", price: 2099, stock: 15 },
      ],
      specs: [
        { key: "Waterproof", value: "IPX7" },
        { key: "Battery", value: "12 Hours" },
        { key: "Power Bank", value: "Built-in (5000mAh)" },
        { key: "Connectivity", value: "Bluetooth 5.0" },
        { key: "Sound", value: "360° Surround" },
      ],
      tags: ["speaker", "bluetooth", "portable", "waterproof", "jbl"],
      rating: 4.6,
      numReviews: 278,
    },
    {
      name: "Wristwatch – Minimalist Dial",
      title: "Men's Minimalist Quartz Wristwatch with Mesh Strap",
      price: 3499,
      discountPrice: 2599,
      description: "Elegant minimalist watch with a clean sunray dial, brushed stainless steel mesh band, Miyota quartz movement, and 5ATM water resistance.",
      shortDescription: "Minimalist Miyota quartz watch with mesh strap.",
      image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&q=80",
      gallery: [],
      category: "Accessories",
      subCategory: "Watches",
      brand: "Daniel Wellington",
      stock: 38,
      sku: "ACC-WATCH-020",
      lowStockThreshold: 5,
      weight: 0.12,
      dimensions: { length: 25, width: 4, height: 2 },
      seoTitle: "Minimalist Quartz Wristwatch | Daniel Wellington",
      seoDescription: "Buy men's minimalist mesh strap wristwatch online.",
      slug: "minimalist-mesh-wristwatch-mens",
      status: "Active",
      visibility: "Public",
      attributes: { size: false, color: true, material: false },
      variations: [
        { color: "Silver/White Dial", price: 2599, stock: 15 },
        { color: "Gold/Black Dial", price: 2799, stock: 13 },
        { color: "Rose Gold/Cream Dial", price: 2799, stock: 10 },
      ],
      specs: [
        { key: "Movement", value: "Miyota Quartz" },
        { key: "Case Material", value: "Stainless Steel" },
        { key: "Strap", value: "Mesh Band" },
        { key: "Water Resistance", value: "5ATM" },
        { key: "Case Diameter", value: "40mm" },
      ],
      tags: ["watch", "minimalist", "quartz", "men", "accessories"],
      rating: 4.5,
      numReviews: 121,
    },
  ];

  // Attach vendor user ID to all products
  const docs = products.map((p) => ({ ...p, user: userId }));

  const result = await Product.insertMany(docs, { ordered: false });
  console.log(`\n🎉  Successfully inserted ${result.length} products!\n`);

  await mongoose.disconnect();
  console.log("🔌  Disconnected from MongoDB");
}

main().catch((err) => {
  console.error("❌  Seed failed:", err.message);
  process.exit(1);
});
